---

- name: Configurando Modprobe
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name:  Configurando Iptables Kubernetes
  copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  become: true

- name : Aplicando reglas kubernetes
  shell: sysctl --system
  become: true
