---

- name: Set ipetables
  shell: |
    update-alternatives --set iptables /usr/sbin/iptables-legacy
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

#sudo add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker Engine.
  apt: 
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Creando el daemon de docker
  file:
    path: /etc/docker/daemon.json
    state: touch

- name: Escribiendo el daemon
  copy: 
    dest: /etc/docker/daemon.json
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }

- name: Enable service docker, and enable persistently
  service: 
    name: docker
    enabled: yes

- name: Reload daemons
  shell: systemctl daemon-reload

- name: Reiniciando
  reboot:
