---

- include_tasks: 01-swap.yaml
- include_tasks: 02-set-hosts.yaml
- include_tasks: 03-firewall.yaml
- include_tasks: 04-docker.yaml
- include_tasks: 05-kubernetes.yaml
- include_tasks: 07-set-time.yaml
- include_tasks: 08-nfs-utils.yaml